name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - id: install-deps
        name: Install Dependencies
        run: |
          bun install

      - id: all-in-one-check
        name: All-In-One Check
        run: |
          bun prepublish
      
      - id: e2e-test
        name: E2E Test
        run: |
          bun run preview &
          bun run test:e2e
